POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Introduction to Machine Learning",
  "author": "Vivek0712",
  "url": "https://dev.to/vivek0712/introduction-to-machine-learning-12c9",
  "userId": "611ea63491338c094c9eda31"
}