POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "HopeL",
  "password": "hopesecret"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "VanB",
  "password": "wrong"
}